<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <NuGetAudit>false</NuGetAudit>
    <AssemblyName>S2SModTemplate</AssemblyName>
    <RootNamespace>MOD_NAMESPACE</RootNamespace>
    <IsWindows>$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))</IsWindows>
    <IsMacOS>$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))</IsMacOS>
    <IsLinux>$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))</IsLinux>
    <ProcessArchitecture>$([System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture)</ProcessArchitecture>

    <SteamAppName>Slay the Spire 2</SteamAppName>

    <SteamCommonDir Condition="'$(IsWindows)' == 'True'">$(MSBuildProgramFiles32)\Steam\steamapps\common\$(SteamAppName)</SteamCommonDir>
    <SteamCommonDir Condition="'$(IsMacOS)' == 'True'">$(HOME)/Library/Application Support/Steam/steamapps/common/$(SteamAppName)</SteamCommonDir>
    <SteamCommonDir Condition="'$(IsLinux)' == 'True'">$(HOME)/.local/share/Steam/steamapps/common/$(SteamAppName)</SteamCommonDir>

    <SteamManagedDir Condition="'$(IsWindows)' == 'True'">$(SteamCommonDir)\data_sts2_windows_x86_64</SteamManagedDir>
    <SteamManagedDir Condition="'$(IsLinux)' == 'True'">$(SteamCommonDir)/data_sts2_linuxbsd_x86_64</SteamManagedDir>
    <SteamManagedDir Condition="'$(IsMacOS)' == 'True' and '$(ProcessArchitecture)' == 'Arm64'">$(SteamCommonDir)/SlayTheSpire2.app/Contents/Resources/data_sts2_macos_arm64</SteamManagedDir>
    <SteamManagedDir Condition="'$(IsMacOS)' == 'True' and '$(ProcessArchitecture)' == 'X64'">$(SteamCommonDir)/SlayTheSpire2.app/Contents/Resources/data_sts2_macos_x86_64</SteamManagedDir>
    <SteamManagedDir Condition="'$(IsMacOS)' == 'True' and '$(SteamManagedDir)' == ''">$(SteamCommonDir)/SlayTheSpire2.app/Contents/Resources/data_sts2_macos_arm64</SteamManagedDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="GodotSharp">
      <HintPath>$(SteamManagedDir)/GodotSharp.dll</HintPath>
    </Reference>
    <Reference Include="Steamworks.NET">
      <HintPath>$(SteamManagedDir)/Steamworks.NET.dll</HintPath>
    </Reference>
    <Reference Include="sts2">
      <HintPath>$(SteamManagedDir)/sts2.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(SteamManagedDir)/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="S2SModTemplate.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
